# Release workflow for the liked/subscribed-only fork.
name: Build Allowed-Only APKs

on:
  workflow_dispatch:
    inputs:
      nightly:
        description: 'Nightly workflow.'
        required: true
        type: boolean
        default: false

jobs:
  # FRANCOTIRADOR: Únicamente la versión universal para TV Box y Móviles
  android-arm:
    uses: ./.github/workflows/main.yaml
    permissions:
      packages: write
      pull-requests: write
    with:
      platform: android-arm
      nightly: ${{ github.event.inputs.nightly }}
    secrets:
      datadog_api_key: ${{ secrets.DD_API_KEY }}