on:
  workflow_call:
    inputs:
      platform:
        description: 'Cobalt platform.'
        required: true
        type: string
      nightly:
        description: 'Nightly workflow.'
        required: true
        type: string
      run_api_leak_detector:
        description: 'Whether to run the api leak detector.'
        required: false
        type: boolean
        default: false
    secrets:
      datadog_api_key:
        required: false
      sccache_gcs_key:
        required: false

concurrency:
  group: ${{ github.workflow }}-${{ inputs.platform }} @ ${{ github.head_ref || github.sha }}-${{ github.ref }}
  cancel-in-progress: true

env:
  CI_ESSENTIALS: |
    .github
    cobalt/build
    cobalt/docker
    cobalt/testing/browser_tests/tools
    cobalt/testing/filters
    cobalt/tools

jobs:
  initialize:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
    env:
      DEPOT_TOOLS_UPDATE: 0
      DEPOT_TOOLS_REPORT_BUILD: 0
      DEPOT_TOOLS_COLLECT_METRICS: 0
      DEPOT_TOOLS_METRICS: 0
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    timeout-minutes: 10
    steps:
      - name: Restore CI Essentials
        uses: actions/checkout@v4
        with:
          fetch-depth: 1
          filter: blob:none
          sparse-checkout: ${{ env.CI_ESSENTIALS }}
      - name: Set platforms
        id: set-platforms
        shell: bash
        run: |
          set -x
          platforms=$(cat ${GITHUB_WORKSPACE}/.github/config/${{ inputs.platform }}.json | jq -c '.platforms')
          echo "platforms=${platforms}" >> $GITHUB_OUTPUT
      - name: Select build runners
        id: set-build-runners
        shell: bash
        run: |
          set -x
          build_runners='["ubuntu-latest"]'
          echo "build_runners=${build_runners}" >> $GITHUB_OUTPUT
      - name: Set build targets
        id: set-targets
        shell: bash
        run: |
          set -x
          targets=$(cat ${GITHUB_WORKSPACE}/.github/config/${{ inputs.platform }}.json | jq -cr '.targets')
          echo "targets=${targets}" >> $GITHUB_OUTPUT
      - name: Set build configs
        id: set-build-configs
        shell: bash
        run: |
          set -x
          # HACK: Forzamos a que SOLO se compile la version final GOLD
          build_configs='["gold"]'
          echo "build_configs=${build_configs}" >> $GITHUB_OUTPUT
      - name: Set platform extra includes
        id: set-includes
        shell: bash
        run: |
          set -x
          includes=$(cat ${GITHUB_WORKSPACE}/.github/config/${{ inputs.platform }}.json | jq -c '.includes')
          echo "includes=${includes}" >> $GITHUB_OUTPUT
      - name: Set root target for unit tests
        id: set-test-root-target
        shell: bash
        run: |
          set -x
          test_root_target=$(cat ${GITHUB_WORKSPACE}/.github/config/${{ inputs.platform }}.json | jq -rc '.test_root_target')
          echo "test_root_target=${test_root_target}" >> $GITHUB_OUTPUT
      - name: Set enable sccache
        id: set-enable-sccache
        shell: bash
        run: |
          set -x
          enable_sccache=$(cat ${GITHUB_WORKSPACE}/.github/config/${{ inputs.platform }}.json | jq -rc '.enable_sccache')
          echo "enable_sccache=${enable_sccache}" >> $GITHUB_OUTPUT
    outputs:
      platforms: ${{ steps.set-platforms.outputs.platforms }}
      build_runners: ${{ steps.set-build-runners.outputs.build_runners }}
      targets: ${{ steps.set-targets.outputs.targets }}
      build_configs: ${{ steps.set-build-configs.outputs.build_configs }}
      includes: ${{ steps.set-includes.outputs.includes }}
      test_root_target: ${{ steps.set-test-root-target.outputs.test_root_target }}
      enable_sccache: ${{ steps.set-enable-sccache.outputs.enable_sccache }}

  build:
    needs: [initialize]
    permissions: {}
    runs-on: ${{ fromJSON(needs.initialize.outputs.build_runners) }}
    name: ${{ matrix.name }}_${{ matrix.config }}
    strategy:
      fail-fast: false
      matrix:
        platform: ${{ fromJson(needs.initialize.outputs.platforms) }}
        include: ${{ fromJson(needs.initialize.outputs.includes) }}
        config: ${{ fromJson(needs.initialize.outputs.build_configs) }}
    env:
      TEST_ARTIFACTS_KEY: ${{ matrix.platform }}_${{ matrix.name }}_test_artifacts
      DEPOT_TOOLS_UPDATE: 0
      DEPOT_TOOLS_REPORT_BUILD: 0
      DEPOT_TOOLS_COLLECT_METRICS: 0
      DEPOT_TOOLS_METRICS: 0
      IS_CI: 1
    steps:
      - name: Set TMPDIR
        shell: bash
        run: |
          set -x
          if [[ -w /__w/_temp/ ]]; then
            echo "TMPDIR=/__w/_temp" >> $GITHUB_ENV
          else
            echo "TMPDIR=${{ runner.temp }}" >> $GITHUB_ENV
          fi
      - name: Restore CI Essentials
        uses: actions/checkout@v4
        with:
          fetch-depth: 1
          filter: blob:none
          sparse-checkout: ${{ env.CI_ESSENTIALS }}

      # ELIMINAMOS la basura del Overlay Workspace que daba el error de permisos
      
      - name: Checkout
        uses: ./.github/actions/checkout
        with:
          path: cobalt/src
          ref: ${{ github.sha }}
          fetch_depth: ${{ ( github.event_name == 'pull_request' || github.repository == 'youtube/cobalt_sandbox' ) && 2 || 0 }}
          use_cache: true

      - name: Set Up Depot Tools
        id: setup-depot-tools
        uses: ./.github/actions/depot_tools
        with:
          use_gcloud: false

      - name: Build Cobalt
        id: build
        uses: ./.github/actions/build
        if: ${{ ! (contains(matrix.platform, 'android') && matrix.config == 'debug') }}
        with:
          targets: ${{ needs.initialize.outputs.targets }}
          test_root_target: ${{ needs.initialize.outputs.test_root_target }}
          test_targets_json_file: out/${{ matrix.platform }}_${{ matrix.config }}/test_targets.json
          enable_sccache: ${{ needs.initialize.outputs.enable_sccache == 'true' }}
          sccache_gcs_key: ${{ secrets.sccache_gcs_key }}

      - name: Release Package
        if:  (matrix.config == 'qa' || matrix.config == 'gold')
        continue-on-error: true
        uses: ./.github/actions/package
        with:
          package_dir: out/test-package